os: linux
cache: false

env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

notifications:
  slack: 
    rooms:
      - isvtepluginworkspace:INkEQdIdxKwlCaGFXx63APPd
    template:
      - "%{repository_slug} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
      - "%{repository_slug}: your GitHub repo identifier (like svenfuchs/minimal)"
      - "%{repository_name}: the slug without the username"
      - "%{build_number}: build number"
      - "%{build_id}: build id"
      - "%{branch}: branch build name"
      - "%{commit}: shortened commit SHA"
      - "%{author}: commit author name"
      - "%{commit_message}: commit message of build"
      - "%{commit_subject}: first line of the commit message"
      - "%{result}: result of build"
      - "%{message}: travis message to the build"
      - "%{duration}: total duration of all builds in the matrix"
      - "%{elapsed_time}: time between build start and finish"
      - "%{compare_url}: commit change view URL"
      - "%{build_url}: URL of the build detail"
      


before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- mkdir -p ~/.config/sfdx
- echo '["isvte-sfdx-plugin"]' > ~/.config/sfdx/unsignedPluginAllowList.json
- sfdx plugins --core
- sfdx plugins:install isvte-sfdx-plugin

script:
- sfdx force:source:convert -d .mdout
- sfdx isvte:mdscan -d .mdout
