os: linux
cache: false

env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
- RESULT="Placeholder"

notifications:
  slack: isvtepluginworkspace:INkEQdIdxKwlCaGFXx63APPd
    template:
      - "%{repository_slug} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
      - "Results: %{RESULT}"

before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- mkdir -p ~/.config/sfdx
- echo '["isvte-sfdx-plugin"]' > ~/.config/sfdx/unsignedPluginAllowList.json
- sfdx plugins --core
- sfdx plugins:install isvte-sfdx-plugin

script:
- sfdx force:source:convert -d .mdout
- RESULT=`sfdx isvte:mdscan -d .mdout`
