os: linux
cache: false

env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

notifications:
  slack: 
    rooms:
      - isvtepluginworkspace:INkEQdIdxKwlCaGFXx63APPd
      


before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- mkdir -p ~/.config/sfdx
- echo '["isvte-sfdx-plugin"]' > ~/.config/sfdx/unsignedPluginAllowList.json
- sfdx plugins --core
- sfdx plugins:install isvte-sfdx-plugin

script:
- sfdx force:source:convert -d .mdout > results.txt
- sfdx isvte:mdscan -d .mdout > results.json

after_script:
- curl -F file=@results.txt -F "initial_comment=ISVTE Plugin Results" -F channels=C022VLWQ3HS -H "Authorization: Bearer xoxb-2076772047031-2121444365426-zmUCf3Diaft8ubJ4mNMlGC9O" https://slack.com/api/files.upload
